#!/bin/bash

# PR submission script for naming and structure compliance fixes
# Generated by Cline (governance_observer_agent_v1)

echo "Starting PR submission for Phase 19.2 structure and naming fixes..."

# Set variables
BRANCH_NAME="fix/phase19-structure-compliance"
PR_TITLE="Fix: Naming and Structure Compliance for Phase 19.2"
PR_BODY_FILE="pull_request.md"
COMMIT_MSG_FILE="commit_message.txt"
TARGET_BRANCH="main"

# Validate files exist
if [ ! -f "$PR_BODY_FILE" ]; then
  echo "Error: PR body file $PR_BODY_FILE not found."
  exit 1
fi

if [ ! -f "$COMMIT_MSG_FILE" ]; then
  echo "Error: Commit message file $COMMIT_MSG_FILE not found."
  exit 1
fi

# Create and checkout new branch
echo "Creating branch: $BRANCH_NAME"
git checkout -b $BRANCH_NAME

# Run the rules check to validate fixes
echo "Validating compliance with rules..."
npm run check:rules

if [ $? -ne 0 ]; then
  echo "Warning: Rule compliance check failed. Please review before proceeding."
  read -p "Continue anyway? (y/n): " CONTINUE
  if [ "$CONTINUE" != "y" ]; then
    echo "Aborting PR creation."
    exit 1
  fi
fi

# Stage all changes
echo "Staging changes..."
git add agents/ logs/ scripts/ docs/logs/

# Commit changes with message from file
echo "Committing changes..."
git commit -F $COMMIT_MSG_FILE

# Push branch to remote
echo "Pushing branch to remote..."
git push -u origin $BRANCH_NAME

# Create PR using GitHub CLI (if available)
if command -v gh &> /dev/null; then
  echo "Creating PR using GitHub CLI..."
  gh pr create --title "$PR_TITLE" --body-file $PR_BODY_FILE --base $TARGET_BRANCH
  
  # Add labels
  gh pr edit --add-label "governance" --add-label "structure" --add-label "fix"
else
  echo "GitHub CLI not found. Please create the PR manually with:"
  echo "- Title: $PR_TITLE"
  echo "- Body: Contents of $PR_BODY_FILE"
  echo "- Base branch: $TARGET_BRANCH"
  echo "- Compare branch: $BRANCH_NAME"
  echo "- Labels: governance, structure, fix"
  echo ""
  echo "PR can be created at: https://github.com/username/forgeborn-core/compare/$BRANCH_NAME?expand=1"
fi

echo "PR submission process complete."
