# trigger_log.yaml
version: 1.0
generated_at: 2024-04-22T16:05:00Z
policy_id: trust-policy-prod-001

triggers:
  - id: trig-prod-014
    blueprint_id: bp-prod-019
    type: fallback_rate
    threshold: 0.25
    observed: 0.31
    status: pending-review
    created_by: system
    created_at: 2024-04-22T14:00:00Z
    reviewers_required:
      - security
      - qa
    reviewer_log: []

  - id: trig-core-041
    blueprint_id: bp-core-041
    type: override_ratio
    threshold: 0.10
    observed: 0.11
    status: pending-review
    created_by: system
    created_at: 2024-04-22T14:03:00Z
    reviewers_required:
      - security
      - cto
    reviewer_log: []
