import { executeGitHubAgent } from './core/github_agent_core.mjs';

const main = async () => {
  await executeGitHubAgent({
    branch: 'feature/auto-pr',
    title: '🤖 Auto-generated update',
    body: 'This pull request was generated by Forgeborn using github_agent_v1.'
  });
};

main();
